parameters: {}
environment: {}
packages:
    - name: calculate
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: add
          binary: false
          main: ""
          web: true
          runtime: go:default
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}